server:
  port: 8100
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/authDB?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/authDB?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

    username: root
#    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    password: smznfrkn
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#security:
#  oauth2:
#    resource:
#      token-info-uri: http://localhost:8100/oauth/check_token
#    client:
#      client-id: bigcart
#      client-secret: pin


logging:
  level:
    org:
      hibernate:
        type: trace
# -------------------------Zuul----------------------------
zuul:
  routes:

    UserManagement-Service:
      url: http://localhost:9988
    products-service:
      url: http://localhost:8001
    orders-service:
      url: http://localhost:8000
    notifications-service:
      url: http://localhost:8006

management:
  endpoints:
    web:
      exposure:
        include: '*'
